### ISSUE TITLE
Add simple local server

### ISSUE THREAD

**Issue by borfast** [borfast/arrispwgen#10]
A local server providing a web interface for generating passwords.

**Comment by rucko24** [comment]
Hi my big dog, With Electron maybe?

**Comment by borfast** [comment]
Hi. Thanks for the suggestion. Electron is meant for graphical user interface applications, not servers, though. And even for GUIs it's a humongous beast. It would take something that takes less than 500 KB and turn it into a 100 MB monster, so it's far from appropriate for this.

**Comment by rucko24** [comment]
Well, electron no, so you want to say something like this?

http://tylerwatt12.com/potd/

**Comment by borfast** [comment]
Yes, I mean a simple HTTP server a user can launch on his machine, maybe even have a simple API.

Why is that funny?

It doesn't exclude the possibility of a GUI application, which would also make sense (though I would still prefer to use something else other than Electron). I just meant that for a _server_ Electron would not be the appropriate choice.

**Comment by rucko24** [comment]
You know that I like vaadin flow, it is a web framework for server and client, very modern, since the code with which I solved the password of the day was with the java code, I like java, I want to do a UI with vaadin flow for this.

So we are looking for a light web framework maybe?

**Comment by borfast** [comment]
You can create a UI for this in Java, if you want. It's the beauty of open source software, anyone can contribute :)
