### ISSUE TITLE
DES encoded 

### ISSUE THREAD

**Issue by anagia** [borfast/arrispwgen#23]
I will like to know what he's the DES encoded of MPSJKMDHAI ,the arris password of the day tool hes not showing the DES encoded
Thankyu

**Comment by borfast** [comment]
Hello @anagia,

Sorry, I don't know what the DES encoded version of the key is because that depends on the encryption key.

**Comment by anagia** [comment]
![sample](https://user-images.githubusercontent.com/23702330/123620583-a284ad80-d7c7-11eb-8c5d-1ba8e1af1c38.png)

![sample2](https://user-images.githubusercontent.com/23702330/123623158-5c7d1900-d7ca-11eb-8b0e-aea85444dcaf.png)



How does the tool calculate the key? 
MPSJKMDHAI (10 letters, the password tool of the day only allows 8 letters)
Do you think it is possible to find out the encryption key of MPSJKMDHAI (DES encoded)? 
Thank you very much !
