### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by XW-git** [borfast/arrispwgen#31]
PS C:\Users\xianw\arrispwgen> npm install @borfast/arrispwge
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@borfast%2farrispwge - Not found
npm ERR! 404
npm ERR! 404  '@borfast/arrispwge@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xianw\AppData\Local\npm-cache\_logs\2022-08-22T18_58_52_509Z-debug-0.log
PS C:\Users\xianw\arrispwgen>

after clone the source ode. I npm install, failed by:
'@borfast/arrispwge@*' is not in this registry.
Is there something missing?

thanks

**Comment by borfast** [comment]
> Is there something missing?

Yes, an `n`  at the end of the package name - it's `@borfast/arrispwgen` and not `@borfast/arrispwge` :wink:

**Comment by XW-git** [comment]
I'm sorry made a silly mistake.
after correcting it, install passed. but how do I bring up the WebPage to generate PoTD? 
many thanks
Xian

**Comment by borfast** [comment]
Maybe it's not clear in the [description](https://github.com/borfast/arrispwgen#description) but this is _just the library_, not the web page.

**Comment by XW-git** [comment]
then how could I make use of the library? do you have a example?
best regards

**Comment by borfast** [comment]
I'm starting to have the feeling you didn't really look at the [documentation](https://github.com/borfast/arrispwgen#how-to-use), did you? :wink: 

You can also look at the [CLI project](https://github.com/borfast/arrispwgen-cli) to see how it is used there.
