### ISSUE TITLE
Seed in Hex

### ISSUE THREAD

**Issue by mrlinux** [borfast/arrispwgen#7]
Hi,
how do i use a seed from snmp that is in hex with this tool?

**Comment by borfast** [comment]
Hi @mrlinux,

You need to convert the seed from hexadecimal notation to regular characters and then use it in the password generator.

**Comment by mrlinux** [comment]
Hi,
is this standard ascii or utf8?
When i do this, i get only crap and some unprintable chars...

**Comment by borfast** [comment]
Should be plain ASCII characters only.
If what you're getting is not ASCII, I would risk saying that it's not the seed.
Can you share more details of your findings?

**Comment by mrlinux** [comment]
its in the SNMP MIB Object(unknown OID 1.3.6.1.4.1.4115.1.3.4.1.2.3.0):1.3.6.1.4.1.4115.1.3.4.1.2.3.0, Octet String,

you have any mail, dont want to disclose the seed of the teco here

**Comment by borfast** [comment]
Sure, you can use my username @ my username .com, or you can drop me a line using my website's contact form: http://www.borfast.com/contact

**Comment by mrlinux** [comment]
i tried already, you script fails on the google mail api...

**Comment by mrlinux** [comment]
sent you to username @ my username .com

**Comment by borfast** [comment]
I just tried my contact form - holy crap! I had no idea that was happening! Have to fix that ASAP. But I did get an email from you, so I'll reply to that in a few minutes.

**Comment by vs0uz4** [comment]
@borfast 

any news regarding the new "seed"

**Comment by borfast** [comment]
@vs0uz4, well, there's no single seed, it depends on your modem and your ISP. More specifically, it depends on whether your ISP changed the default seed, and what it was.

Also, just like the other one you also commented on, this is a closed issue and unrelated to your question. There are better ways to ask for help, like commenting on the project page.
